language: go

go:
  - tip

install:
  - go get gopkg.in/check.v1
  - go get github.com/gorilla/mux
  - go get github.com/golang/lint/golint
  - ln -s ${TRAVIS_BUILD_DIR} $HOME/gopath/src/github.com/fake_validator

script:
  - go vet ./...
  - golint ./...
  - go test ./... -cover
